- name: Backup Old source.list
  file:
    path: /etc/apt/sources.list
    state: absent

- name: Copy New source.list
  template:
    src: "source.list.j2"
    dest: "/etc/apt/sources.list"
    owner: "root"
    group: "root"
    mode: "0644"
  notify: Update Mirrors Cache

